### ISSUE TITLE
Possible Redundancy in Checkpoint Size Check

### ISSUE THREAD

**Issue by SwardHorse** [sigstore/rekor-monitor#328]
**Description**
Hello,
I was reviewing the source code and came across what appears to be a redundancy in the checking of checkpoint size in file main.go. The code snippet is as follows:
```go
if prevCheckpoint == nil || prevCheckpoint.Size != checkpoint.Size {
    if err := file.WriteCheckpoint(checkpoint, *logInfoFile); err != nil {
        return fmt.Errorf("failed to write checkpoint: %v", err)
    }
}
```
and
```go
if prevCheckpoint != nil && prevCheckpoint.Size != checkpoint.Size {
    ...
}
```
In the first block, the condition `prevCheckpoint.Size != checkpoint.Size` implies that `prevCheckpoint != nil`. Therefore, the first condition could be simplified to `prevCheckpoint == nil`.

However, more importantly, this could lead to a logic error where logic that is intended to be handled by the second block is being handled by the first block due to the redundancy in the condition. This could potentially lead to serious issues in the execution of the code.

I suggest simplifying the first condition to not only improve the code readability and performance, but also to prevent potential logic errors. If there is a specific reason for this implementation, I would appreciate it if you could explain it to me.

And if it do is a problem, can i push a pr? I'll be very cheerful.

Thank you for your time and consideration.

**Comment by haydentherapper** [comment]
Hi, thanks for the looking at the code! This is intentional, and I don't believe there is an issue with this logic, though feel free to let me know if the following seems incorrect.

`prevCheckpoint` is only initialized when there was a previous run of the monitor. In the first conditional, if no monitor run has occurred, we should write the current checkpoint. The next check is if to catch if we've run the monitor recently - if the monitor runs within a few minutes of a previous monitor run, then the checkpoint should be the same and so we skip writing the duplicated checkpoint.

In the second conditional, we first check if we're not on the first run (`prevCheckpoint != nil`) and then check if the checkpoint size is different (meaning the monitor is processing a new point in time in the log).

If the first conditional is simplified, we'll write a duplicated checkpoint, which provides no benefit.
